-- Versioned record of the GF-4 schema already applied to the remote project.
-- Do not apply this file again to the configured remote project.
create table public.customers (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null check (char_length(btrim(name)) between 2 and 100 and name = btrim(name)),
  phone text not null default '' check (char_length(phone) <= 30),
  email text not null default '' check (char_length(email) <= 320),
  notes text not null default '' check (char_length(notes) <= 500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, owner_id)
);
create table public.work_orders (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  customer_id uuid not null,
  order_number bigint generated by default as identity (start with 1001),
  order_code text generated always as ('OS-' || order_number::text) stored,
  title text not null,
  description text not null default '',
  value_cents bigint not null default 0 check (value_cents >= 0),
  status text not null default 'new' check (status in ('new', 'in_progress', 'waiting', 'completed')),
  service_date date not null,
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (customer_id, owner_id) references public.customers(id, owner_id)
);
create function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;
create trigger customers_updated_at before update on public.customers for each row execute function public.set_updated_at();
create trigger work_orders_updated_at before update on public.work_orders for each row execute function public.set_updated_at();
alter table public.customers enable row level security;
alter table public.work_orders enable row level security;
revoke all on public.customers, public.work_orders from anon;
grant select, insert, update on public.customers, public.work_orders to authenticated;
grant usage on sequence public.work_orders_order_number_seq to authenticated;
create policy customers_select_own on public.customers for select to authenticated using ((select auth.uid()) = owner_id);
create policy customers_insert_own on public.customers for insert to authenticated with check ((select auth.uid()) = owner_id);
create policy customers_update_own on public.customers for update to authenticated using ((select auth.uid()) = owner_id) with check ((select auth.uid()) = owner_id);
create policy work_orders_select_own on public.work_orders for select to authenticated using ((select auth.uid()) = owner_id);
create policy work_orders_insert_own on public.work_orders for insert to authenticated with check ((select auth.uid()) = owner_id);
create policy work_orders_update_own on public.work_orders for update to authenticated using ((select auth.uid()) = owner_id) with check ((select auth.uid()) = owner_id);
